services:
  postgres:
    image: postgres:16-alpine     # фиксируем стабильную версию
    container_name: postgres-game-swap
    environment:
      POSTGRES_DB: gameswap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-game-swap
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  security-network:
    driver: bridge