spring.application.name=GameSwap

jwt.secret=e23@421k9d3k92093fk02-324r0(4)--
jwt.access.expiration=900000
jwt.refresh.expiration=1209600000


spring.datasource.url=jdbc:postgresql://localhost:5432/gameswap
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true